server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UTeamFactory/perustars-configdata.git
          username: ${BANKING_GIT_USER}
          password: ${BANKING_GIT_TOKEN}
          default-label: "main"
          searchPaths: artwork-service, event-service, report-service
          cloneOnStart: true