server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/UTeamFactory/config-data.git
          username: ${BANKING_GIT_USER}
          password: ${BANKING_GIT_TOKEN}
          default-label: "master"
          searchPaths: artworks-service, events-service, reports-service
          cloneOnStart: true